config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'orders/index'

  match 'orders/getreport' => 'orders#getreport', via: [:get, :post]

  get 'orders/index', as: 'user_root'
 
  resources :orders
  resources :places
  resources :photos do
    get :download, on: :collection
    delete :delete, on: :member
  end
	resources :users, path: 'staff'

  post 'set_todays_place' => 'users#set_todays_place'

  root 'orders#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registerable, :recoverable
	devise :database_authenticatable, :rememberable, :trackable, :recoverable

  EMAIL_REGEXP = /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i
	ROLES = %i[user admin]

  belongs_to :current_place, class_name: 'Place'
  has_many :orders
  has_many :photos

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: EMAIL_REGEXP }
  validates :password, length: { within: 6..18 }, unless: :skip_password?

  after_commit :send_info_letter, on: :create

  def today_current_place
    if current_place && current_place_set_at >= (Time.now.hour >= 8 ? Time.now.change(hour: 8) : 1.day.ago.change(hour: 8))
      current_place
    else
      nil
    end
  end

  def role?(role_name)
    role == role_name
  end

  def skip_password?
    @skip_password ||= false
  end

  def update_without_password(params, *options)
    instance_variable_set(:@skip_password, true)
    result = super
    instance_variable_set(:@skip_password, false)
    result
  end

  private

  def send_info_letter
    UserInfoMailer.send_user_info(self.id, self.password).deliver_later
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :check_admin, except: :set_todays_place
  before_action :find_user, only: [:show, :edit, :update, :destroy]
	before_action

	def index
    @users = User.all
  end

	def show
  end

  def new
    @user = User.new
  end

  def edit
	end

  def create
  	@user = User.new(save_params)
 
  	if @user.save
  	 redirect_to @user
    else
      render :new
    end
  end

  def update
  	if @user.update_without_password(save_params)
    	redirect_to @user
  	else
    	render 'edit'
  	end
	end

	def destroy
  	@user.destroy
  	redirect_to users_path
	end

  def set_todays_place
    place = Place.find_by_name(params[:place_name])
    User.where(id: current_user.id).update_all(current_place_id: place.id, current_place_set_at: Time.now) if place
  end


  private

  def find_user
    @user = User.find(params[:id])
  end
  def save_params
    params.require(:user).permit(:email, :role, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def options_for_role
  		[
    			['Administrator','admin'],
    			['Waiter','user'],
  		]
	end
end

app/views/users/_form.html.haml
/ = form_for @user do |f|
/   - if @user.errors.any?
/     #error_explanation
/       %h2.heading
/         = pluralize(@user.errors.count, "error")
/         prohibited
/         this user from being saved:
/       %ul
/         - @user.errors.full_messages.each do |msg|
/           %li= msg
/   %p.field
/     = f.label :email
/     %br/
/     = f.text_field :email
/   %p.field
/     = f.label :role
/     %br/
/     = f.select :role, options_for_role
/   %p.field-up
/     = f.submit

= simple_form_for @user do |f|
  %p.field
    = label_tag 'Email'
    = f.input :email, label: false
  %p.field
    = label_tag 'Role'
    =f.input :role, collection: options_for_role, label: false, include_blank: false
  - unless @user.id
    %p.field
      = label_tag 'Password'
      =f.input :password, label: false
  = f.submit 'Save'

app/views/users/edit.html.erb
<div class="promo-form promo-form-center">

	<h1>Edit user</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', users_path %>

</div>

app/views/users/index.html.erb
<div class="promo-form promo-form-center">

  <h1 class="heading">Listing Users</h1>

  <span class="add-new"><%= link_to 'add new user', new_user_path %></span>

  <div class="table-wrapper">
    <table class="table-in users-table">
      <tr class="table-in__first-tr">
        <th>ID</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
     
      <% @users.each do |user| %>
        <tr>
          <td data-label="ID"><%= user.id %></td>
          <td data-label="Email"><%= user.email %></td>
          <td data-label="Role"><%= user.role?('admin') ? 'Admin' : 'Waiter' %></td>
          <td class="no-padding-right"><button class="button button-show"><%= link_to 'Show', user_path(user) %></button></td>
          <td class="no-padding-right padding-left"><button class="button button-edit"><%= link_to 'Edit', edit_user_path(user) %></button></td>
          <td class="no-padding-right padding-left"><button class="button button-delete">
            <%= link_to 'Destroy', user_path(user),
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %>
          </button></td>
        </tr>
      <% end %>
    </table>
  </div>


</div>

app/views/users/new.html.erb
<div class="promo-form promo-form-center">

	<h1>New user</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', users_path %>

</div>

app/views/users/show.html.erb
<div class="promo-form promo-form-center">

	<p class="table-text">
	  <strong>Email:</strong>
	  <%= @user.email %>
	</p>
	 
	<p class="role">
	  <strong>Role:</strong>
	  <%= @user.role?('admin') ? 'Admin' : 'Waiter' %>
	</p>

	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Back', users_path %>

</div>