config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'orders/index'

  match 'orders/getreport' => 'orders#getreport', via: [:get, :post]

  get 'orders/index', as: 'user_root'
 
  resources :orders
  resources :places
  resources :photos do
    get :download, on: :collection
    delete :delete, on: :member
  end
	resources :users, path: 'staff'

  post 'set_todays_place' => 'users#set_todays_place'

  root 'orders#index'
end

app/models/order.rb
class Order < ApplicationRecord
  before_save :set_price

  Based = ['on_water','on_fresh_juice','on_milk']
  Aqua = ['apple','grapefruit','melon','pineapple','watermelon_hookan']

  belongs_to :place
  belongs_to :user

  validates :based, :aqua, :place, :user, :date, presence: true
  
  attr_accessor :date_from, :date_to

  def set_price
    if (aqua == 'watermelon_hookan')
      check = 'watermelon_hookan'
    else 
      check = aqua + "_" + based
    end

    self.currency = place.currency
    self.total = place[check]
  end

  def self.month_days(month,year=Date.today.year)
    mdays = [nil,31,28,31,30,31,30,31,31,30,31,30,31]
    mdays[2] = 29 if Date.leap?(year)
    mdays[month]
  end

  def self.create_report(order_params,params)
    @start_date = Time.mktime(Date.today.year,params[:month],01,00,00,0)
    @end_day = month_days(params[:month].to_i)
    @end_date = Time.mktime(Date.today.year,params[:month],@end_day,23,59,59)
    @orderlist = Order.where("place ==? AND date > ? AND date < ?",order_params[:place],@start_date,@end_date)
    @calc = {}

    Aqua.each do |aqua|
      Based.each do |based|
        @i = 1
        @calc["#{aqua}_#{based}"] = {}
        while @i <= @end_day do
          @calc["#{aqua}_#{based}"]["#{@i}"] = 0
          @i += 1
        end
      end
    end

    @orderlist.each do |child|
        @calc["#{child[:aqua]}_#{child[:based]}"]["#{child[:date].day}"] += 1
    end
    @calc
  end

  def self.generate_report(period_start, period_end, place_id)
    variants = []
    Order::Aqua.each{|a| Order::Based.each{|b| variants<<[a,b]}}
    periods = (period_start.to_date..period_end.to_date).group_by{|d| "#{Date::MONTHNAMES[d.month]} #{d.year}"}.map { |k,v| [k, v.first.beginning_of_month, v.first.end_of_month] }
    periods_data = []
    periods.each do |p|
      from = p.second
      to = p.last
      counts = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).group("(date_trunc('day', date), orders.based, orders.aqua)").count
      totals = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).group("(orders.based, orders.aqua)").count
      day_total = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).group("date_trunc('day', date)").count
      total_profits = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).group("(orders.based, orders.aqua)").sum(:total)
      sum_total = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).group("orders.aqua").count
      sum_total_profits = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).group("orders.aqua").sum(:total)
      watermelon_hookan_counts = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).where(aqua: 'watermelon_hookan').group("date_trunc('day', date)").count
      watermelon_hookan_total = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).where(aqua: 'watermelon_hookan').count
      watermelon_hookan_profits = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).where(aqua: 'watermelon_hookan').sum(:total)
      total_count = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).count
      total_profit = Order.where(place_id: place_id).where('date >= ?', from.beginning_of_day).where('date <= ?', to.end_of_day).sum(:total)

      periods_data << {
        period_name: p.first,
        period_start: from,
        period_end: to,
        counts: counts,
        totals: totals,
        day_total: day_total,
        total_profits: total_profits,
        sum_total: sum_total,
        sum_total_profits: sum_total_profits,
        variants: variants,
        watermelon_hookah: {
          counts: watermelon_hookan_counts,
          total: watermelon_hookan_total,
          profits: watermelon_hookan_profits
        },
        total_count: total_count,
        total_profit: total_profit
      }
    end
    periods_data
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_current_place, only: :create
  before_action

  def index
    @from = Date.strptime(params[:order][:date_from], "%d.%m.%Y") rescue 1.day.ago.beginning_of_day
    @to = Date.strptime(params[:order][:date_to], "%d.%m.%Y").end_of_day rescue Date.today.end_of_day
    
    @orders = (current_user.role?('admin') ? Order.all : current_user.orders).where(created_at: @from..@to).order('created_at DESC').paginate(page: params[:page], per_page: 10)
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
    authorize! :update, @order
  end

  def create
    @order = current_user.orders.new(save_params.merge(place: current_user.today_current_place, date: Time.now))
    authorize! :create, @order
    if @order.save
      redirect_to orders_path, notice: 'Order created'
    else
      redirect_to orders_path, alert: 'Order was not created'
    end
  end

  def update
    @order = Order.find(params[:id])
    authorize! :update, @order
    @order.date = Time.now
    if @order.update(save_params)
      redirect_to orders_path, notice: 'Order updated'
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    authorize! :destroy, @order
    @order.destroy
    redirect_to orders_path
  end


  def getreport
    @from = Date.strptime(params[:order][:date_from], "%m-%Y") rescue Date.today.beginning_of_month
    @to = Date.strptime(params[:order][:date_to], "%m-%Y") rescue Date.today
    @place = Place.find(params[:order][:place_id]) rescue Place.first
    @report = Order.generate_report(@from, @to, @place.id)
    @total = @place.earnings(@from, @to)
    respond_to do |format|
      format.html
      format.xls
    end

  end


  private

  def check_current_place
    unless current_user.today_current_place
      flash[:alert] = "Chose place for today first"
      redirect_to orders_path, alert: "Chose place for today first"
    end
  end

  def save_params
    params.require(:order).permit(:based, :aqua, :place_id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper

	def options_for_based
  		[
    			['On water','on_water'],
    			['On fresh juice','on_fresh_juice'],
    			['On milk','on_milk']
  		]
	end

	def options_for_aqua
  		[
    			['On apple','apple'],
    			['On Grapefruit','grapefruit'],
    			['On Melon','melon'],
    			['On Pineaple','pineapple'],
    			['Watermelon Hookah','watermelon_hookan']
  		]
	end

  def options_for_month
      [
          ['On apple','0'],
          ['On Grapefruit','1'],
          ['On Melon','2'],
          ['On Pineaple','3'],
          ['Watermelon Hookah','watermelon_hookan']
      ]
  end
end

app/views/orders/_form.html.haml
= simple_form_for(@order) do |f|
  %p.field
    = label_tag 'Base' 
    = f.input :based, collection: options_for_based, label: false
  %p.field
    = label_tag 'Fruit'
    = f.input :aqua, collection: options_for_aqua, label: false
  %p.field
    = label_tag 'Place'
    = f.input :place_id, collection: Place.order(:name).all.map{|p| [p.name, p.id]}, label: false   
  = f.button :submit, "Submit"

app/views/orders/_index_form.html.haml
= simple_form_for(@order) do |f|
  %p.field
    = label_tag 'Base' 
    = f.input :based, collection: options_for_based, label: false
  %p.field
    = label_tag 'Fruit'
    = f.input :aqua, collection: options_for_aqua, label: false
    
  = f.button :submit, "Create"

app/views/orders/_table.html.haml
%div.table-wrapper.table-month_datas-wrapper
  - @report.each do |month_data|
    %table.table-in
      %tr.tr-month
        %td{colspan: 3}= month_data[:period_name]
        %td.td-place-name{colspan: (month_data[:period_end]-month_data[:period_start]+5).to_i}= @place.name
      %tr.tr-figures
        %td{colspan: 3, rowspan: 2} Shishas
        - (month_data[:period_start]..month_data[:period_end]).each do |day|
          %td=day.strftime('%a').first 
        %td.td-total-color{rowspan: 2} Total/type
        %td.td-total-color.min-width{rowspan: 2} $ by type
        %td.td-total-color.min-width{rowspan: 2} Total mois
        %td.td-total-color.min-width{rowspan: 2} Total $
      %tr.tr-figures
        - (month_data[:period_start]..month_data[:period_end]).each do |day|
          %td=day.strftime('%d')
      - (1..12).each do |id|
        %tr
          -if id.in?([1,4,7,10])
            %td{rowspan: 3}= month_data[:variants][id-1].first
          %td= month_data[:variants][id-1].second
          %td= @place.send(month_data[:variants][id-1].join('_'))
          - (month_data[:period_start]..month_data[:period_end]).each do |day|
            %td= month_data[:counts]["(\"#{day.to_time.to_s(:db)}\",#{month_data[:variants][id-1].second},#{month_data[:variants][id-1].first})"] || 0
          %td= month_data[:totals]["(#{month_data[:variants][id-1].second},#{month_data[:variants][id-1].first})"] || 0
          %td= month_data[:total_profits]["(#{month_data[:variants][id-1].second},#{month_data[:variants][id-1].first})"] || 0
          -if id.in?([1,4,7,10])
            %td{rowspan: 3}= month_data[:sum_total][month_data[:variants][id-1].first] || 0 
            %td{rowspan: 3}= month_data[:sum_total_profits][month_data[:variants][id-1].first] || 0
      %tr
        %td{colspan: 2} Watermelon hookah
        %td= @place.watermelon_hookan
        - (month_data[:period_start]..month_data[:period_end]).each do |day|
          %td= month_data[:watermelon_hookah][:counts][day.beginning_of_day] || 0
        - 2.times do
          %td= month_data[:watermelon_hookah][:total]
          %td= month_data[:watermelon_hookah][:profits]
      %tr
        %td.td-total-color{colspan: 3} Total by day
        - (month_data[:period_start]..month_data[:period_end]).each do |day|
          %td= month_data[:day_total][day.beginning_of_day] || 0
        %td= month_data[:total_count]
        %td= month_data[:total_profit]
        %td= month_data[:total_count]
        %td= month_data[:total_profit]
      %tr 
        %td{colspan: (month_data[:period_end]-month_data[:period_start]+6).to_i, rowspan: 2}
        %td Divers
        %td
      %tr
        %td.td-total-color Total
        %td.td-total-color= month_data[:total_profit]
    %br

  %table.table-in{style: "float: right;"}
    %tr
      %td.td-total-color Grand Total:
      %td.td-total-color= @total

app/views/orders/edit.html.erb
<div class="promo-form promo-form-center">

	<h1>Edit orders</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', orders_path %>

</div>

app/views/orders/getreport.html.haml
%div.promo-form.promo-form-new.promo-form-report 
  %h1.heading.heading-report Report
  = simple_form_for Order.new(date_from: @from.strftime('%m-%Y'), date_to: @to.strftime('%m-%Y'), place_id: @place.id), method: :post, url: orders_getreport_path do |f|
    %div.report-form
      = f.input :date_from, as: :string, input_html: { class: "datepicker" }
      = f.input :date_to, as: :string, input_html: { class: "datepicker" }
      = f.input :place_id, collection: Place.all.order('name ASC').map{|p| [p.name, p.id]}, include_blank: false
      = f.button :submit, "Generate", data: {disable_with: false}
      = f.button :submit, "Generate XLSX", formaction: "#{orders_getreport_path}.xls", data: {disable_with: false}

  #table_report.table-reports
    = render partial: "table"

app/views/orders/getreport.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
 <Styles>
    <Style ss:ID="s62">
     <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
     </Borders>
    </Style>
  </Styles>
  <Worksheet ss:Name="<%= @place.name %>">
    <Table>
      <% @report.each do |month_data| %>
        <Row>
          <Cell><Data ss:Type="String"><%= month_data[:period_name]%></Data></Cell>
          <Cell><Data ss:Type="String"></Data></Cell>
          <Cell><Data ss:Type="String"><%= @place.name%></Data></Cell>
        </Row>
        <Row>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Shishas</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"></Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"></Data></Cell>
          <% (month_data[:period_start]..month_data[:period_end]).each do |day| %>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= day.strftime('%a').first %></Data></Cell>
          <% end %>
        </Row>
        <Row>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Fruit</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Base</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Price</Data></Cell>
          <% (month_data[:period_start]..month_data[:period_end]).each do |day| %>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= day.strftime('%d') %></Data></Cell>
          <% end %>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Total/type</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String">$ by type</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Total mois</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Total $</Data></Cell>
        </Row>
        <% (1..12).each do |id|  %>
          <Row>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:variants][id-1].first %></Data></Cell>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:variants][id-1].second %></Data></Cell>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= @place.send(month_data[:variants][id-1].join('_')) %></Data></Cell>
            <% (month_data[:period_start]..month_data[:period_end]).each do |day| %>
              <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:counts]["(\"#{day.to_time.to_s(:db)}\",#{month_data[:variants][id-1].second},#{month_data[:variants][id-1].first})"] || 0 %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:totals]["(#{month_data[:variants][id-1].second},#{month_data[:variants][id-1].first})"] || 0 %></Data></Cell>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:total_profits]["(#{month_data[:variants][id-1].second},#{month_data[:variants][id-1].first})"] || 0 %></Data></Cell>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:sum_total][month_data[:variants][id-1].first] || 0 if id.in?([1,4,7,10]) %></Data></Cell>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:sum_total_profits][month_data[:variants][id-1].first] || 0 if id.in?([1,4,7,10]) %></Data></Cell>
          </Row>
        <% end %>
        <Row>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Watermelon hookah</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"></Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"><%= @place.watermelon_hookan %></Data></Cell>
          <% (month_data[:period_start]..month_data[:period_end]).each do |day| %>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:watermelon_hookah][:counts][day.beginning_of_day] || 0 %></Data></Cell>
          <% end %>
          <% 2.times do %>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:watermelon_hookah][:total] %></Data></Cell>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:watermelon_hookah][:total] %></Data></Cell>
          <% end %>
        </Row>
        <Row>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Total by day</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"></Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"></Data></Cell>
          <% (month_data[:period_start]..month_data[:period_end]).each do |day| %>
            <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:day_total][day.beginning_of_day] || 0 %></Data></Cell>
          <% end %>
          <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:total_count] %></Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:total_profit] %></Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:total_count] %></Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:total_profit] %></Data></Cell>
        </Row>
        <Row>
          <% (month_data[:period_end]-month_data[:period_start]+6).to_i.times do %>
            <Cell><Data ss:Type="String"></Data></Cell>
          <% end %>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Divers</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"></Data></Cell>
        </Row>
        <Row>
          <% (month_data[:period_end]-month_data[:period_start]+6).to_i.times do %>
            <Cell><Data ss:Type="String"></Data></Cell>
          <% end %>
          <Cell ss:StyleID="s62"><Data ss:Type="String">Total</Data></Cell>
          <Cell ss:StyleID="s62"><Data ss:Type="String"><%= month_data[:total_profit] %></Data></Cell>
        </Row>
        <Row></Row>
      <% end %>

      <Row>
        <% (@report.last[:period_end]-@report.last[:period_start]+6).to_i.times do %>
          <Cell><Data ss:Type="String"></Data></Cell>
        <% end %>
        <Cell ss:StyleID="s62"><Data ss:Type="String">Grand Total</Data></Cell>
        <Cell ss:StyleID="s62"><Data ss:Type="String"><%= @total %></Data></Cell>
      </Row>
    </Table>
  </Worksheet>
</Workbook>

app/views/orders/index.html.haml
.promo-form.promo-form-center.promo-form-orders
  .order
    %h1.order__heading
      Serving in
      .order__place.place
        .place__name
          %a#placeName.text-value{:href => "#"}= current_user.today_current_place ? current_user.today_current_place.name : 'CHOOSE PLACE'
      %ul.place__list.dropdown-menu.list.hide
        - Place.all.each do |p|
          %li
            %a.list__link= p.name

  .order__form
    = render 'index_form'

  - if current_user.role? 'admin'
    = simple_form_for Order.new(date_from: @from.strftime('%d.%m.%Y'), date_to: @to.strftime('%d.%m.%Y')), method: :get, url: orders_path do |f|
      %div.report-form
        %h1.heading Filter 
        = f.input :date_from, as: :string, input_html: { class: "datepicker-date" }
        = f.input :date_to, as: :string, input_html: { class: "datepicker-date" }
        = f.button :submit, "Filter", data: {disable_with: false}

  .table-wrapper.table-orders-wrapper
    %table.table-in.orders-table
      %tr.table-in__first-tr
        %th(data-label="#") #
        %th.th-total(data-label="Total") Total
        %th.th-time(data-label="Time") Time
        - if current_user.role? 'admin'
          %th.th-waiter(data-label="Waiter") Waiter
          %th.th-place(data-label="Place") Place
      - @orders.each do |order|
        %tr.orders-tr
          %td(data-label="#")= order.id
          %td.td-total(data-label="Total")= "#{order.total.to_f.round(2)} €"
          %td.td-time(data-label="Time")= order.date.strftime('%d.%m.%Y %H:%M:%S %Z')
          - if current_user.role? 'admin'
            %td.td-waiter(data-label="Waiter")= order.user.try(:email)
            %td.td-place(data-label="Place")= order.place.try(:name)
          - if can? :update, order
            %td.no-padding-right.td-edit
              %button.button.button-edit= link_to 'Edit', edit_order_path(order)
          - if can? :destroy, order
            %td.no-padding-right.padding-left.td-delete
              %button.button.button-delete= link_to 'Destroy', order_path(order), |
                  method: :delete,                      |
                  data: { confirm: 'Are you sure?' }    |
    = will_paginate(@orders) 

app/views/orders/show.html.haml
.promo-form.promo-form-new
  %p.table-text
    %strong Id:
    = @order.id
  %p.table-text
    %strong Date:
    = @order.date.strftime('%d.%m.%Y %H:%M:%S %Z')
  %p.table-text
    %strong Place:
    = @order.place.try(:name)
  %p.table-text
    %strong Based:
    = @order.based
  %p.table-text
    %strong Fruit:
    = @order.aqua
  %p.table-text.role
    %strong Total:
    = @order.total
  = link_to 'Edit', edit_order_path(@order)
  |
  \#{link_to 'Back', orders_path}