config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'orders/index'

  match 'orders/getreport' => 'orders#getreport', via: [:get, :post]

  get 'orders/index', as: 'user_root'
 
  resources :orders
  resources :places
  resources :photos do
    get :download, on: :collection
    delete :delete, on: :member
  end
	resources :users, path: 'staff'

  post 'set_todays_place' => 'users#set_todays_place'

  root 'orders#index'
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :orders

  validates :name, :currency, presence: true
  validates_numericality_of :apple_on_fresh_juice, :apple_on_milk, :apple_on_water,
   :grapefruit_on_fresh_juice, :grapefruit_on_milk, :grapefruit_on_water, :melon_on_fresh_juice, :melon_on_milk, 
   :melon_on_water, :pineapple_on_fresh_juice, :pineapple_on_milk, :pineapple_on_water, :watermelon_hookan, greater_than: 0


  def earnings(from, to)
    Order.where(place_id: self.id).where('date >= ?', from.beginning_of_month.beginning_of_day).where('date <= ?', to.end_of_month.end_of_day).sum(:total)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!
  before_action :check_admin

	def index
    @places = Place.all
  end

	def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def edit
  	@place = Place.find(params[:id])
	end

  def create
  	@place = Place.new(save_params)
 
  	if @place.save
  	 redirect_to places_path, notice: 'Place created'
    else
      render :new
    end
  end

  def update
  	@place = Place.find(params[:id])
 
  	if @place.update(save_params)
    	redirect_to places_path, notice: 'Place updated'
  	else
    	render 'edit'
  	end
	end

	def destroy
  	@place = Place.find(params[:id])
  	@place.destroy
 
  	redirect_to places_path
	end

  private
  def save_params
    params.require(:place).permit(:name, :currency,:apple_on_fresh_juice,:apple_on_milk,:apple_on_water,:grapefruit_on_fresh_juice,:grapefruit_on_milk,:grapefruit_on_water,:melon_on_fresh_juice,:melon_on_milk,:melon_on_water,:pineapple_on_fresh_juice,:pineapple_on_milk,:pineapple_on_water,:watermelon_hookan)
  end

end

app/helpers/places_helper.rb
module PlacesHelper
	def options_for_currency
  		[
    			['Euro','euro'],
    			['Chf','chf'],
  		]
	end
end

app/views/places/_form.html.haml
= form_for @place do |f|
  - if @place.errors.any?
    #error_explanation
      %h2.heading
        = pluralize(@place.errors.count, "error")
        prohibited
        this place from being saved:
      %ul
        - @place.errors.full_messages.each do |msg|
          %li= msg
  %p.field
    = f.label :name
    %br/
    = f.text_field :name
  %p.field
    = f.label :currency
    %br/
    = f.select :currency, options_for_currency
  %p.field
    = f.label :apple_on_fresh_juice
    %br/
    = f.text_field :apple_on_fresh_juice
  %p.field
    = f.label :apple_on_milk
    %br/
    = f.text_field :apple_on_milk
  %p.field
    = f.label :apple_on_water
    %br/
    = f.text_field :apple_on_water
  %p.field
    = f.label :grapefruit_on_fresh_juice
    %br/
    = f.text_field :grapefruit_on_fresh_juice
  %p.field
    = f.label :grapefruit_on_milk
    %br/
    = f.text_field :grapefruit_on_milk
  %p.field
    = f.label :grapefruit_on_water
    %br/
    = f.text_field :grapefruit_on_water
  %p.field
    = f.label :melon_on_fresh_juice
    %br/
    = f.text_field :melon_on_fresh_juice
  %p.field
    = f.label :melon_on_milk
    %br/
    = f.text_field :melon_on_milk
  %p.field
    = f.label :melon_on_water
    %br/
    = f.text_field :melon_on_water
  %p.field
    = f.label :pineapple_on_fresh_juice
    %br/
    = f.text_field :pineapple_on_fresh_juice
  %p.field
    = f.label :pineapple_on_milk
    %br/
    = f.text_field :pineapple_on_milk
  %p.field
    = f.label :pineapple_on_water
    %br/
    = f.text_field :pineapple_on_water
  %p.field
    = f.label :watermelon_hookan
    %br/
    = f.text_field :watermelon_hookan
  %p.field-up
    = f.submit

app/views/places/edit.html.erb
<div class="promo-form promo-form-center promo-form-long">

	<h1>Edit places</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', places_path %>

</div>

app/views/places/index.html.erb
<div class="promo-form promo-form-center">

  <h1>Listing recs</h1>

  <span class="add-new"><%= link_to 'new place', new_place_path %></span>
  <div class="table-wrapper">
    <table class="table-in places-table">
      <tr class="table-in__first-tr">
        <th>ID</th>
        <th>Name</th>
        <th>Currency</th>
      </tr>
     
      <% @places.each do |place| %>
        <tr>
          <td><%= place.id %></td>
          <td><%= place.name %></td>
          <td><%= place.currency %></td>
          <td class="no-padding-right"><button class="button button-show"><%= link_to 'Show', place_path(place) %></button></td>
          <td class="no-padding-right padding-left"><button class="button button-edit"><%= link_to 'Edit', edit_place_path(place) %></button></td>
          <td class="no-padding-right padding-left"><button class="button button-delete"><%= link_to 'Destroy', place_path(place),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></button></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/places/new.html.erb
<div class="promo-form promo-form-center promo-form-long">

	<h1>New place</h1>
	 
		<%= render 'form' %>

	<%= link_to 'Back', places_path %>

</div>

app/views/places/show.html.erb
<div class="promo-form promo-form-center">
	<p class="table-text">
	  <strong>Name:</strong>
	  <%= @place.name %>
	</p>
	 
	<p class="table-text role">
	  <strong>Currency:</strong>
	  <%= @place.currency %>
	</p>

	<%= link_to 'Edit', edit_place_path(@place) %> |
	<%= link_to 'Back', place_path %>
</div>