config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'orders/index'

  match 'orders/getreport' => 'orders#getreport', via: [:get, :post]

  get 'orders/index', as: 'user_root'
 
  resources :orders
  resources :places
  resources :photos do
    get :download, on: :collection
    delete :delete, on: :member
  end
	resources :users, path: 'staff'

  post 'set_todays_place' => 'users#set_todays_place'

  root 'orders#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Smokinghot
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0, user-scalable=no", :name => "viewport"}/
    %script{:src => "https://unpkg.com/sweetalert/dist/sweetalert.min.js"}
  %body{class: (user_signed_in? && current_user.role?('admin')) ? 'admin clearfix' : 'clearfix' }
    - if user_signed_in?
      .user
        %span.user-in
          Hello, #{current_user.email}
        %span.user-logout= link_to 'Logout', destroy_user_session_path, method: :delete
      - if current_user.role == 'admin'
        %div.menu.btn3
          %div.icon
        %div.admin-navigation-wrapper
          %table.admin-navigation
            %tr
              / %td.admin-td
              /   %strong Admin:
              %td= link_to 'Orders', orders_path
              %td= link_to 'Users', users_path
              %td= link_to 'Places', places_path
              %td= link_to 'Report', orders_getreport_path
              %td= link_to 'Invoices', photos_path
      - else
        %div.menu.btn3
          %div.icon
        %div.admin-navigation-wrapper
          %table.admin-navigation
            %tr
              %td= link_to 'Orders', orders_path
              %td= link_to 'Invoices', photos_path
    - else
      .user-no
        = link_to 'Login', new_user_session_path
    - flash.each do |key, value|
      %div{:class => "alert alert-#{key}"}= value.html_safe
    .promo-form
      = yield
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'